#!/usr/bin/env bash
set -euo pipefail

MIYA_ROOT="$(cd "$(dirname "$0")" && pwd)"
BRANCH="${MIYA_BRANCH:-main}"

# ── Helpers ──────────────────────────────────────────────────────

_ensure_uv() {
    if command -v uv &>/dev/null; then
        return
    fi
    echo "[miya] uv not found. Installing..."
    if [[ "$(uname)" == "Darwin" ]] && command -v brew &>/dev/null; then
        brew install uv
    else
        curl -LsSf https://astral.sh/uv/install.sh | sh
        # shellcheck disable=SC1091
        source "$HOME/.local/bin/env" 2>/dev/null || true
    fi
    if ! command -v uv &>/dev/null; then
        echo "[miya] Error: uv installation failed. Install manually: https://docs.astral.sh/uv/"
        exit 1
    fi
    echo "[miya] uv installed successfully."
}

_ensure_deps() {
    cd "$MIYA_ROOT"
    uv sync --extra dev --quiet 2>/dev/null || uv sync --extra dev
}

_link_bin() {
    # Create a wrapper script so `miya` works from any directory
    local bin_dir="$HOME/.local/bin"
    mkdir -p "$bin_dir"

    cat > "$bin_dir/miya" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by miya installer. Project: $MIYA_ROOT
exec "$MIYA_ROOT/.venv/bin/miya" "\$@"
WRAPPER
    chmod +x "$bin_dir/miya"

    # Check if bin_dir is on PATH
    if [[ ":$PATH:" != *":$bin_dir:"* ]]; then
        echo ""
        echo "[miya] ~/.local/bin is not on your PATH. Add it:"
        local shell_name
        shell_name="$(basename "${SHELL:-bash}")"
        local rc_file="$HOME/.${shell_name}rc"
        if [[ "$shell_name" == "zsh" ]]; then
            rc_file="$HOME/.zshrc"
        elif [[ "$shell_name" == "bash" ]]; then
            rc_file="$HOME/.bashrc"
        fi
        echo ""
        echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> $rc_file"
        echo "  source $rc_file"
        echo ""
    fi
}

_unlink_bin() {
    local bin_path="$HOME/.local/bin/miya"
    if [[ -f "$bin_path" ]]; then
        rm -f "$bin_path"
        echo "[miya] Removed $bin_path"
    else
        echo "[miya] Not installed at $bin_path"
    fi
}

# ── Main ─────────────────────────────────────────────────────────

CMD="${1:-help}"
shift 2>/dev/null || true

case "$CMD" in
    install)
        echo "[miya] Installing from $MIYA_ROOT ..."
        _ensure_uv
        cd "$MIYA_ROOT"
        uv sync
        _link_bin
        echo ""
        echo "[miya] Installed successfully."
        echo "[miya] Run: miya health"
        ;;
    install-dev)
        echo "[miya] Installing (dev mode) from $MIYA_ROOT ..."
        _ensure_uv
        cd "$MIYA_ROOT"
        uv sync --extra dev
        _link_bin
        echo ""
        echo "[miya] Dev install complete."
        ;;
    uninstall)
        _unlink_bin
        echo "[miya] Uninstalled."
        ;;
    test)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run pytest -v "$@"
        ;;
    test-unit)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run pytest tests/unit -v "$@"
        ;;
    test-int)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run pytest tests/integration -v "$@"
        ;;
    test-e2e)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run pytest tests/e2e -v "$@"
        ;;
    test-cov)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run pytest --cov=miya --cov-report=term-missing "$@"
        ;;
    lint)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run ruff check miya tests "$@"
        ;;
    fmt)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run ruff format miya tests "$@"
        ;;
    run)
        _ensure_uv; _ensure_deps
        cd "$MIYA_ROOT"
        uv run miya "$@"
        ;;
    update)
        _ensure_uv
        cd "$MIYA_ROOT"
        echo "[miya] Pulling latest from origin/$BRANCH..."
        git fetch origin "$BRANCH"
        git reset --hard "origin/$BRANCH"
        uv sync --extra dev
        _link_bin
        echo "[miya] Updated to $(git rev-parse --short HEAD)"
        ;;
    help)
        echo "Usage: ./run.sh <command> [args...]"
        echo ""
        echo "Commands:"
        echo "  install      Install miya + create 'miya' command on PATH"
        echo "  install-dev  Install with dev deps (pytest, ruff)"
        echo "  uninstall    Remove 'miya' command from PATH"
        echo "  update       Pull latest from git + re-sync deps"
        echo ""
        echo "  run          Run miya CLI (e.g. ./run.sh run health)"
        echo "  test         Run all tests"
        echo "  test-unit    Run unit tests"
        echo "  test-int     Run integration tests"
        echo "  test-e2e     Run e2e tests"
        echo "  test-cov     Run tests with coverage"
        echo "  lint         Run ruff linter"
        echo "  fmt          Auto-format code"
        echo ""
        echo "Environment:"
        echo "  MIYA_BRANCH  Git branch for update (default: main)"
        ;;
    *)
        echo "Unknown command: $CMD"
        echo "Run: ./run.sh help"
        exit 1
        ;;
esac
